[project]
name = "zubale-adk"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "google-adk",
    "google-cloud-aiplatform[agent-engine]>=1.106.0",
    "opik>=1.8.13",
    "yfinance",
]
